"""Canonical error code strings.

Codes are part of the public surface (operation logs, metrics, dashboards
reference them). Adding a new code is non-breaking; renaming one is breaking.
"""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    # LLM
    LLM_RATE_LIMIT = "LLM_RATE_LIMIT"
    LLM_TIMEOUT = "LLM_TIMEOUT"
    LLM_SERVER_ERROR = "LLM_SERVER_ERROR"
    LLM_CONTEXT_OVERFLOW = "LLM_CONTEXT_OVERFLOW"
    LLM_INVALID_RESPONSE = "LLM_INVALID_RESPONSE"
    LLM_AUTH = "LLM_AUTH"
    LLM_BAD_REQUEST = "LLM_BAD_REQUEST"

    # Tools
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    TOOL_ARG_VALIDATION = "TOOL_ARG_VALIDATION"
    TOOL_EXEC = "TOOL_EXEC"
    TOOL_TIMEOUT = "TOOL_TIMEOUT"
    MCP_BRIDGE_OFFLINE = "MCP_BRIDGE_OFFLINE"
    MCP_BRIDGE_STARTUP = "MCP_BRIDGE_STARTUP"

    # Storage
    STORAGE_SQLITE_UNAVAILABLE = "STORAGE_SQLITE_UNAVAILABLE"
    STORAGE_PG_UNAVAILABLE = "STORAGE_PG_UNAVAILABLE"
    STORAGE_INTEGRITY = "STORAGE_INTEGRITY"
    STORAGE_MIGRATION = "STORAGE_MIGRATION"

    # Operation logs
    OPLOG_VALIDATION = "OPLOG_VALIDATION"
    OPLOG_INTEGRITY = "OPLOG_INTEGRITY"
    OPLOG_CONFLICT = "OPLOG_CONFLICT"

    # Pipeline / orchestrator
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
    UNKNOWN_PROJECT = "UNKNOWN_PROJECT"
    PIPELINE_STATE_INCONSISTENT = "PIPELINE_STATE_INCONSISTENT"
    JIRA_TRANSITION_FORBIDDEN = "JIRA_TRANSITION_FORBIDDEN"
    JIRA_TRANSITION_INVALID = "JIRA_TRANSITION_INVALID"
    STAGE_RETRY_EXHAUSTED = "STAGE_RETRY_EXHAUSTED"

    # Jira / GitHub clients
    JIRA_AUTH = "JIRA_AUTH"
    JIRA_NOT_FOUND = "JIRA_NOT_FOUND"
    JIRA_SERVER_ERROR = "JIRA_SERVER_ERROR"
    GH_AUTH = "GH_AUTH"
    GH_NOT_FOUND = "GH_NOT_FOUND"
    GH_SERVER_ERROR = "GH_SERVER_ERROR"
    GH_SCOPE = "GH_SCOPE"

    # Guardrail
    GUARD_INPUT_BLOCKED = "GUARD_INPUT_BLOCKED"
    GUARD_OUTPUT_BLOCKED = "GUARD_OUTPUT_BLOCKED"
    GUARD_ACTION_REFUSED = "GUARD_ACTION_REFUSED"
    GUARD_MISCONFIGURED = "GUARD_MISCONFIGURED"

    # Config
    CONFIG_VALIDATION = "CONFIG_VALIDATION"
    CONFIG_MISSING = "CONFIG_MISSING"
    CONFIG_FILE = "CONFIG_FILE"
